export default {
  items: [
    {
      name: 'ADMIN SITE',
      url: '/dashboard',
      icon: 'icon-speedometer',
      badge: {
        variant: 'info',
        text: 'NEW',
      },
    },
    {
      title: true,
      name: 'Quản lý sự kiện',
      wrapper: {            // optional wrapper object
        element: '',        // required valid HTML5 element tag
        attributes: {}        // optional valid JS object with JS API naming ex: { className: "my-class", style: { fontFamily: "Verdana" }, id: "my-id"}
      },
      class: ''             // optional class names space delimited list for title item ex: "text-center"
    },
    {
      name: 'Danh sách sự kiện',
      url: '/event/event-list',
      icon: 'fas fa-calendar-alt',
    },
     {
      name: 'Danh sách thông báo',
      url: '/event/notification-list',
      icon: 'fas fa-calendar-alt',
    },
    {
      title: true,
      name: 'Quản lý sinh viên',
      wrapper: {
        element: '',
        attributes: {},
      },
    },
    {
      name: 'Khoa CNTT ',
      url: '/base',
      icon: 'fas fa-graduation-cap',
      children: [
        {
          name: 'K59',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K59CNTT1',
              url: '/student-list',
            },
            {name: 'K59CNTT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K59CNTT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K59CNTT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K59CNTT5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K60',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K60CNTT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K60CNTT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K60CNTT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K60CNTT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K60CNTT5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K61',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K61CNTT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K61CNTT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K61CNTT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K61CNTT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K61CNTT5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K62',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K62CNTT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K62CNTT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K62CNTT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K62CNTT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K62CNTT5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K63',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K63CNTT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K63CNTT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K63CNTT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K63CNTT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K63CNTT5',
              url: '/base/breadcrumbs',
            },
          ]
        },
      ],
    },
{
      name: 'Khoa ĐTVT ',
      url: '/base',
      icon: 'fas fa-graduation-cap',
      children: [
        {
          name: 'K59',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K59ĐTVT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K59ĐTVT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K59ĐTVT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K59ĐTVT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K59ĐTVT',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K60',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K60ĐTVT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K60ĐTVT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K60ĐTVT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K60ĐTVT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K60ĐTVT',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K61',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K61ĐTVT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K61ĐTVT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K61ĐTVT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K61ĐTVT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K61ĐTVT',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K62',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K62ĐTVT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K62ĐTVT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K62ĐTVT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K62ĐTVT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K62ĐTVT',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K63',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K63ĐTVT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K63ĐTVT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K63ĐTVT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K63ĐTVT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K63ĐTVT',
              url: '/base/breadcrumbs',
            },
          ]
        },
      ],
    },
{
      name: 'Khoa CKT&TĐH ',
      url: '/base',
      icon: 'fas fa-graduation-cap',
      children: [
        {
          name: 'K59',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K59CKT&TĐH1',
              url: '/base/breadcrumbs',
            },
            {name: 'K59CKT&TĐH2',
              url: '/base/breadcrumbs',
            },
            {name: 'K59CKT&TĐH3',
              url: '/base/breadcrumbs',
            },
            {name: 'K59CKT&TĐH4',
              url: '/base/breadcrumbs',
            },
            {name: 'K59CKT&TĐH5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K60',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K60CKT&TĐH1',
              url: '/base/breadcrumbs',
            },
            {name: 'K60CKT&TĐH2',
              url: '/base/breadcrumbs',
            },
            {name: 'K60CKT&TĐH3',
              url: '/base/breadcrumbs',
            },
            {name: 'K60CKT&TĐH4',
              url: '/base/breadcrumbs',
            },
            {name: 'K60CKT&TĐH5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K61',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K61CKT&TĐH1',
              url: '/base/breadcrumbs',
            },
            {name: 'K61CKT&TĐH2',
              url: '/base/breadcrumbs',
            },
            {name: 'K61CKT&TĐH3',
              url: '/base/breadcrumbs',
            },
            {name: 'K61CKT&TĐH4',
              url: '/base/breadcrumbs',
            },
            {name: 'K61CKT&TĐH5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K62',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K62CKT&TĐH1',
              url: '/base/breadcrumbs',
            },
            {name: 'K62CKT&TĐH2',
              url: '/base/breadcrumbs',
            },
            {name: 'K62CKT&TĐH3',
              url: '/base/breadcrumbs',
            },
            {name: 'K62CKT&TĐH4',
              url: '/base/breadcrumbs',
            },
            {name: 'K62CKT&TĐH5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K63',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K63CKT&TĐH1',
              url: '/base/breadcrumbs',
            },
            {name: 'K63CKT&TĐH2',
              url: '/base/breadcrumbs',
            },
            {name: 'K63CKT&TĐH3',
              url: '/base/breadcrumbs',
            },
            {name: 'K63CKT&TĐH4',
              url: '/base/breadcrumbs',
            },
            {name: 'K63CKT&TĐH5',
              url: '/base/breadcrumbs',
            },
          ]
        },
      ],
    },
{
      name: 'Khoa VLKT ',
      url: '/base',
      icon: 'fas fa-graduation-cap',
      children: [
        {
          name: 'K59',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K59LVKT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K59LVKT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K59LVKT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K59LVKT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K59LVKT5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K60',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K60LVKT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K60LVKT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K60LVKT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K60LVKT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K60LVKT5',
              url: '/base/breadcrumbs',
            },
          ]

        },
        {
          name: 'K61',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K61LVKT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K61LVKT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K61LVKT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K61LVKT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K61LVKT5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K62',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K62LVKT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K62LVKT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K62LVKT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K62LVKT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K62LVKT5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K63',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K63LVKT1',
              url: '/base/breadcrumbs',
            },
            {name: 'K63LVKT2',
              url: '/base/breadcrumbs',
            },
            {name: 'K63LVKT3',
              url: '/base/breadcrumbs',
            },
            {name: 'K63LVKT4',
              url: '/base/breadcrumbs',
            },
            {name: 'K63LVKT5',
              url: '/base/breadcrumbs',
            },
          ]
        },
      ],
    },
{
      name: 'Khoa CNHK ',
      url: '/base',
      icon: 'fas fa-graduation-cap',
      children: [
        {
          name: 'K59',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K59CNHK1',
              url: '/base/breadcrumbs',
            },
            {name: 'K59CNHK2',
              url: '/base/breadcrumbs',
            },
            {name: 'K59CNHK3',
              url: '/base/breadcrumbs',
            },
            {name: 'K59CNHK4',
              url: '/base/breadcrumbs',
            },
            {name: 'K59CNHK5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K60',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K60CNHK1',
              url: '/base/breadcrumbs',
            },
            {name: 'K60CNHK2',
              url: '/base/breadcrumbs',
            },
            {name: 'K60CNHK3',
              url: '/base/breadcrumbs',
            },
            {name: 'K60CNHK4',
              url: '/base/breadcrumbs',
            },
            {name: 'K60CNHK5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K61',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K61CNHK1',
              url: '/base/breadcrumbs',
            },
            {name: 'K61CNHK2',
              url: '/base/breadcrumbs',
            },
            {name: 'K61CNHK3',
              url: '/base/breadcrumbs',
            },
            {name: 'K61CNHK4',
              url: '/base/breadcrumbs',
            },
            {name: 'K61CNHK5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K62',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K62CNHK1',
              url: '/base/breadcrumbs',
            },
            {name: 'K62CNHK2',
              url: '/base/breadcrumbs',
            },
            {name: 'K62CNHK3',
              url: '/base/breadcrumbs',
            },
            {name: 'K62CNHK4',
              url: '/base/breadcrumbs',
            },
            {name: 'K62CNHK5',
              url: '/base/breadcrumbs',
            },
          ]
        },
        {
          name: 'K63',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
          children:[
            {name: 'K63CNHK1',
              url: '/base/breadcrumbs',
            },
            {name: 'K63CNHK2',
              url: '/base/breadcrumbs',
            },
            {name: 'K63CNHK3',
              url: '/base/breadcrumbs',
            },
            {name: 'K63CNHK4',
              url: '/base/breadcrumbs',
            },
            {name: 'K63CNHK5',
              url: '/base/breadcrumbs',
            },
          ]
        },
      ],
    },
  ],
};
